### ISSUE TITLE
Trying to understand the training of PG-GAN with class labels

### ISSUE THREAD

**Issue by prash030** [zhangqianhui/progressive_growing_of_gans_tensorflow#14]
Hi @zhangqianhui 
Thank you for the implementation! It is very helpful.

I have a question, and I was wondering if I can get your thoughts: The paper mentions that their training is unsupervised - meaning that it was not label-conditioned. Then how come they were able to generate label-specific images for LSUN dataset? Did they train separate networks for each label or is their network a multi-class generator?

As a follow-up, does your implementation generate images of input classes (while testing) after training on multiple classes?

Thanks in advance!

**Comment by zhangqianhui** [comment]
https://github.com/zhangqianhui/Conditional-Gans

**Comment by prash030** [comment]
That helps! Thanks for your response
