### ISSUE TITLE
我有一个疑问 

### ISSUE THREAD

**Issue by sankin1770** [zhangqianhui/progressive_growing_of_gans_tensorflow#15]
初次接触GAN,如果问的太基础请见谅  `          

                    realbatch_array = np.clip(realbatch_array, -1, 1)
                    save_images(realbatch_array[0:self.batch_size], [2, self.batch_size/2],
                                '{}/{:02d}_real.jpg'.format(self.sample_path, step))

                    if self.trans and self.pg != 0:
                        low_realbatch_array = np.clip(low_realbatch_array, -1, 1)
                        save_images(low_realbatch_array[0:self.batch_size], [2, self.batch_size / 2],
                                    '{}/{:02d}_real_lower.jpg'.format(self.sample_path, step))
                   
                    fake_image = sess.run(self.fake_images,
                                          feed_dict={self.images: realbatch_array, self.z: sample_z})
                    fake_image = np.clip(fake_image, -1, 1)
                    save_images(fake_image[0:self.batch_size], [2, self.batch_size/2], '{}/{:02d}_train.jpg'.format(self.sample_path, step))`
这里面有一步  `fake_image = sess.run(self.fake_images,
                                          feed_dict={self.images: realbatch_array, self.z: sample_z})` 是不是可以替换成   ```
`fake_image = sess.run(self.fake_images,
                                          feed_dict={ self.z: sample_z})`
```
然后生成的fake和real值不是一一对应的吧  比如是陈冠希  我生成的fake不是陈冠希吧

**Comment by zhangqianhui** [comment]
yes, you are right

SankinPlus <notifications@github.com> 于2019年1月21日周一 下午6:48写道：
