### ISSUE TITLE
train loss is negative,please explain to me ,thanks!

### ISSUE THREAD

**Issue by WWWJL** [zhangqianhui/progressive_growing_of_gans_tensorflow#19]
PG 1, step 0: D loss=0.2648493 G loss=-0.1896488, D_or loss=0.1181762, opt_alpha_tra=0.0000000
PG 1, step 400: D loss=-0.6157230 G loss=0.0674022, D_or loss=-0.8367248, opt_alpha_tra=0.0100000
PG 1, step 800: D loss=-0.1810449 G loss=0.5394976, D_or loss=-0.3036686, opt_alpha_tra=0.0200000
PG 1, step 1200: D loss=-0.0945862 G loss=-0.8442736, D_or loss=-0.2622258, opt_alpha_tra=0.0300000
PG 1, step 1600: D loss=-0.5540385 G loss=0.3731411, D_or loss=-0.6529528, opt_alpha_tra=0.0400000
PG 1, step 2000: D loss=-0.4823601 G loss=0.4856569, D_or loss=-0.5566395, opt_alpha_tra=0.0500000
PG 1, step 2400: D loss=-0.0843895 G loss=0.1010681, D_or loss=-0.1548125, opt_alpha_tra=0.0600000
PG 1, step 2800: D loss=-0.1969025 G loss=0.0634548, D_or loss=-0.2701692, opt_alpha_tra=0.0700000
PG 1, step 3200: D loss=-0.3599952 G loss=0.1829128, D_or loss=-0.3996447, opt_alpha_tra=0.0800000
PG 1, step 3600: D loss=0.1415115 G loss=-0.0370798, D_or loss=0.0640999, opt_alpha_tra=0.0900000
PG 1, step 4000: D loss=-0.0609178 G loss=0.1558231, D_or loss=-0.1338096, opt_alpha_tra=0.1000000
PG 1, step 4400: D loss=-0.4271692 G loss=0.1705226, D_or loss=-0.4995243, opt_alpha_tra=0.1100000
PG 1, step 4800: D loss=-0.1475996 G loss=0.1545829, D_or loss=-0.2413805, opt_alpha_tra=0.1200000
PG 1, step 5200: D loss=-0.0023486 G loss=0.2533301, D_or loss=-0.0623062, opt_alpha_tra=0.1300000
PG 1, step 5600: D loss=-0.3025054 G loss=0.2369120, D_or loss=-0.3451613, opt_alpha_tra=0.1400000
PG 1, step 6000: D loss=-0.0315916 G loss=0.1381170, D_or loss=-0.1310087, opt_alpha_tra=0.1500000
PG 1, step 6400: D loss=-0.0186618 G loss=0.0608674, D_or loss=-0.0837486, opt_alpha_tra=0.1600000
PG 1, step 6800: D loss=-0.1877660 G loss=0.1341513, D_or loss=-0.2104936, opt_alpha_tra=0.1700000
PG 1, step 7200: D loss=-0.0606919 G loss=0.0908021, D_or loss=-0.1625843, opt_alpha_tra=0.1800000
PG 1, step 7600: D loss=-0.0598196 G loss=0.2552856, D_or loss=-0.1427037, opt_alpha_tra=0.1900000
PG 1, step 8000: D loss=-0.1311789 G loss=0.0492419, D_or loss=-0.2045113, opt_alpha_tra=0.2000000
PG 1, step 8400: D loss=-0.1048601 G loss=0.0262296, D_or loss=-0.1693949, opt_alpha_tra=0.2100000

**Comment by zhangqianhui** [comment]
Please the wgan-gp paper: https://arxiv.org/abs/1704.00028
