### ISSUE TITLE
questions about t

### ISSUE THREAD

**Issue by theoldgun** [zhangqianhui/progressive_growing_of_gans_tensorflow#20]
great project~
I have a question,What role does t play?
What difference between 'de_iden ' and 'de'?
Thank you
https://github.com/zhangqianhui/progressive_growing_of_gans_tensorflow/blob/f0c9235af6a45a850c5f081e5115b33073e92851/PGGAN.py#L278

**Comment by zhangqianhui** [comment]
t is : resolution transition process

**Comment by theoldgun** [comment]
Thank you for your reply.
But,the parmater 'alpha_trans' always set 0.Does it right?

**Comment by zhangqianhui** [comment]
No, it's rang is 0 to 1
