### ISSUE TITLE
Hi, I have some questions

### ISSUE THREAD

**Issue by tiantianwahaha** [zhangqianhui/progressive_growing_of_gans_tensorflow#4]
阅读了下你的代码，终于把nvidia这篇文章中的一些小点搞明白了。还有几个问题想咨询一下。
1. low_realbatch_array这个是什么作用，没看明白，alpha功能不是已经通过alpha_trans在G和D中实现了么
2. 请问最大迭代数max_iters是怎么决定为32000的
3. 载入真实图片的时候center_crop，会随机把图片的左右调换，这是为了增加样本多样性吗？
4. 论文中4*4,8*8,16*16,32*32层都还是512，你的从16开始就递减为256,128,64了，这是因为内存不足吗，不知道是否会对结果产生较大的影响
5. 我用的GTX 1080，到pg=6 t=true这一步就提示我CUDA_ERROR_OUT_OF_MEMORY....

可能是我tensorflow版本是最新的，所以有两个地方有问题，我修改了下
1. ops.py 153行 input.shape[0]改为了tf.shape(input)[0]，否则会报错
2. main.py 模型的保存路径，最新版tf是保存为4个文件，没有model.ckpt这个文件了，模型路径需要更改下，否则会生成一个叫model.ckpt的文件夹

问题好像有点多。。非常希望能够解答，或者可以的话加我的QQ46923591

**Comment by zhangqianhui** [comment]
ok,  QQ.
